name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['24', '24']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1.18.0
        with:
          node-version: ${{ matrix.node }}
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Check
        run: vp check

      - name: Test
        run: vp test

      - name: Package
        run: vp pack
